language: node_js
node_js:
  - "stable"
  - "unstable"
  - "iojs"
before_script:
  - npm i grunt-cli
script: "./node_modules/.bin/grunt test"
notifications:
  email:
    on_success: never
    on_failure: always
